<a href="https://colab.research.google.com/github/Pragna235/KMeans-Clustering/blob/main/Clustering_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-Means Clustering

In [1]:
import numpy as np
from sklearn.cluster import KMeans

X = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])
kmeans = KMeans(n_clusters = 2,random_state=0)
kmeans.fit(X)

kmeans.labels_

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([1, 1, 1, 0, 0, 0], dtype=int32)

In [3]:
kmeans.predict([[0,0],[12,3]])

array([1, 0], dtype=int32)

In [4]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])